resolver: lts-9.14

packages:
- '.'
- location:
   git: https://github.com/commercialhaskell/stack.git
   commit: 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4
  extra-dep: true
- location:
   git: https://github.com/NixOS/cabal2nix.git
   commit: cba06639637a6764d78ab11bc0961a6815f699fd
  extra-dep: true

extra-deps:
- hnix-0.3.4
- bindings-uname-0.1
- Cabal-2.0.0.2
- hackage-db-2.0
- path-0.6.1
- path-io-1.3.3

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl]

extra-package-dbs: []

extra-include-dirs: [/usr/local/opt/openssl/include/]
extra-lib-dirs: [/usr/local/opt/openssl/lib/]
